### ISSUE TITLE
Account Creator Bug 

### ISSUE THREAD

**Issue by FinaLBeaTzTv** [Merubokkusu/discord-spam-bots#101]
Type one of the following numbers to launch that spammmer
   +========- Server Spammers -=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults online and spams them
   +========- DM Spammers -=========+
4 : Text Spammer - Write your own text to spam
6 : Insult Spammer - Picks insults online and spams them
   +========- Other -=========+
7 : Join Server - Join the server thats written in the config
   +========- Account Creator -=========+
8 : Account creator - Create bulk accounts
9 : Account verifier - Verify accounts
   +=================+
Select a bot: 8
Starting account creation for: sdfsfsfddsfd@mail.ru
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 81, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 71, in create
    print(currentAcc, ": Discord:", r.json()['message'], 'Retry in seconds: ', r.json()['retry_after'])
KeyError: 'retry_after'

**Comment by MiracleWhip209** [comment]
Same here, did you fix it?
