### ISSUE TITLE
This error?

### ISSUE THREAD

**Issue by developedbyalex** [Merubokkusu/discord-spam-bots#121]
Exception ignored in thread started by: <bound method GatewayServer._heartbeat of <discum.gateway.gateway.GatewayServer object at 0x000002563B341700>>
Traceback (most recent call last):
  File "C:\Users\alexp\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\gateway\gateway.py", line 205, in _heartbeat
    self.send({"op": self.OPCODE.HEARTBEAT,"d": self.sequence-1 if self.sequence>0 else self.sequence})
  File "C:\Users\alexp\AppData\Local\Programs\Python\Python39\lib\site-packages\discum\gateway\gateway.py", line 210, in send
    self.ws.send(json.dumps(payload))
  File "C:\Users\alexp\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 190, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by SebastienTolron** [comment]
Hey , same issue here :/
