### ISSUE TITLE
2Captcha ZERO_BALANCE ERROR

### ISSUE THREAD

**Issue by nicolas1410** [Merubokkusu/discord-spam-bots#126]
**Describe the bug**
When I launch the Account Creator, here is the issue I get:

Starting account creation for: jesusagomar@yahoo.es
Traceback (most recent call last):
  File "C:\Users\nicod\Desktop\RAIDTOOLBOX\discord-spam-bots-master\discord-spam-bots-master\bots\misc\account-creator\account_creator.py", line 81, in <module>
    create()
  File "C:\Users\nicod\Desktop\RAIDTOOLBOX\discord-spam-bots-master\discord-spam-bots-master\bots\misc\account-creator\account_creator.py", line 44, in create
    recaptcha_answer = solver.hcaptcha(sitekey=site_key,url=discordUrl)
  File "C:\Python310\lib\site-packages\twocaptcha\solver.py", line 198, in hcaptcha
    result = self.solve(sitekey=sitekey,
  File "C:\Python310\lib\site-packages\twocaptcha\solver.py", line 403, in solve
    id_ = self.send(**kwargs)
  File "C:\Python310\lib\site-packages\twocaptcha\solver.py", line 457, in send
    response = self.api_client.in_(files=files, **params)
  **File "C:\Python310\lib\site-packages\twocaptcha\api.py", line 76, in in_
    raise ApiException(resp)**
**twocaptcha.api.ApiException: ERROR_ZERO_BALANCE**

I'm on masterfork and windows 11

**Comment by raphaelpalhano** [comment]
I received that too:

com.twocaptcha.exceptions.ApiException: ERROR_ZERO_BALANCE
