### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Someone\Desktop\discord-spam-bots-master\bots\server\discord_text_spam.py", line 8, in <module>     import discum ModuleNotFoundError: No module named 'discum'

### ISSUE THREAD

**Issue by wrrrf** [Merubokkusu/discord-spam-bots#127]
already have discum installed still giving the error

**Comment by itsreyi** [comment]
pip install discum

**Comment by belugaHackz** [comment]
do this

1. win+r
2. type cmd 
3. press enter
4. type pip install discum
5. wait for it to install
6. then run "python (the script name).py
7. look for errors then repeat the process

done

**Comment by this-is-really** [comment]
Started Text Spam Traceback (most recent call last): File "C:\Users\admin\Downloads\discord-spam-bots-master\discord-spam-bots-master\bots\server\discord_text_spam.py", line 61, in <module>
