### ISSUE TITLE
Forbidden Issue

### ISSUE THREAD

**Issue by Kenner-G** [Merubokkusu/discord-spam-bots#14]
LOG: 
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "discord_text_spam_dm.py", line 25, in on_ready
    await client.send_message(member, spam_text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): You are opening direct messages too fast.

**Comment by Kenner-G** [comment]
Okay, updated... Now there is another issue:
LOG:
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "discord_text_spam_dm.py", line 17, in on_ready
    for member in server.members:
RuntimeError: dictionary changed size during iteration

**Comment by Merubokkusu** [comment]
First one is because you reached a limit of sending DMs

Second one is an old bug that's fixed(?) 
Basically someone joined while scraping the server, I'll check tomorrow for another way to fix it.(unless you aren't on the newest push)

**Comment by Merubokkusu** [comment]
_**Should**_ be good now

**Comment by Kenner-G** [comment]
Thanks for getting back to me!
- What is the limit for sending DMs?
- I'll update my directory. :)

**Comment by Merubokkusu** [comment]
![shrug](https://media.giphy.com/media/anB3cor0tgFX2/giphy.gif)
How long were you running the bot?

**Comment by Kenner-G** [comment]
In total, around 5ish hours.

**Comment by Merubokkusu** [comment]
Multiple accounts?

**Comment by Merubokkusu** [comment]
Everything working good now?
