### ISSUE TITLE
error so fucking error 

### ISSUE THREAD

**Issue by glitzhXEC** [Merubokkusu/discord-spam-bots#24]
future: <Task finished coro=<Client.start() done, defined at C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:500> exception=TypeError('login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given',)>
Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 508, in start
    await self.login(*args, bot=bot)
TypeError: login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
Task exception was never retrieved
future: <Task finished coro=<Client.start() done, defined at C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:500> exception=LoginFailure('Improper token has been passed.',)>
Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 508, in start
    await self.login(*args, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 380, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished coro=<Client.start() done, defined at C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:500> exception=LoginFailure('Improper token has been passed.',)>
Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 508, in start
    await self.login(*args, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 380, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished coro=<Client.start() done, defined at C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:500> exception=LoginFailure('Improper token has been passed.',)>
Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 508, in start
    await self.login(*args, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 380, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by Merubokkusu** [comment]
"Improper token has been passed"
Meaning what ever token you put into the bot doesn't work.

**Comment by glitzhXEC** [comment]
how to get token  i use email & passowrd

**Comment by Merubokkusu** [comment]
You can use email and pass like this
Email:password

**Comment by glitzhXEC** [comment]
Task exception was never retrieved
future: <Task finished coro=<Client.start() done, defined at C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:500> exception=TypeError('login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given',)>
Traceback (most recent call last):
  File "C:\Users\imagi\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 508, in start
    await self.login(*args, bot=bot)
TypeError: login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

**Comment by Merubokkusu** [comment]
Anyway I can see the format of your email:pass
You can censor it

**Comment by glitzhXEC** [comment]
![ascaasc](https://user-images.githubusercontent.com/47280575/56752662-fc862480-67b2-11e9-98a1-eee5d7e7f6b0.png)
  
File "C:\Users\imagi\Desktop\discord-spam-bots-master\start.py", line 158, in <module>
    p.wait()
NameError: name 'p' is not defined

**Comment by Merubokkusu** [comment]
Use a token instead,https://discordhelp.net/discord-token

**Comment by glitzhXEC** [comment]
Traceback (most recent call last):
  File "C:\Users\imagi\Desktop\discord-spam-bots-master\start.py", line 158, in <module>
    p.wait()
NameError: name 'p' is not defined
![ascsaca](https://user-images.githubusercontent.com/47280575/56753065-efb60080-67b3-11e9-9b3d-9c2a391dc2be.png)

**Comment by Merubokkusu** [comment]
Python version?
