### ISSUE TITLE
Error When Attempting To Join Server

### ISSUE THREAD

**Issue by vizzual123** [Merubokkusu/discord-spam-bots#35]
Traceback (most recent call last):
  File "bots/misc/joinServer2.0.py", line 23, in <module>
    r = requests.post(url,headers=headers, proxies=PROXY)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\models.py", line 314, in prepare
    self.prepare_headers(headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\models.py", line 448, in prepare_headers
    check_header_validity(header)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\utils.py", line 942, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization
https://discordapp.com/api/v6/invite/CK6KqJN?with_counts=true
Traceback (most recent call last):
  File "bots/misc/joinServer2.0.py", line 23, in <module>
    r = requests.post(url,headers=headers, proxies=PROXY)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.22.0-py3.6.egg\requests\api.py", line 116, in post

**Comment by Merubokkusu** [comment]
From what i see there is a problem with your token.
