### ISSUE TITLE
Have that bug,what i do wrong?

### ISSUE THREAD

**Issue by Jeremy2131** [Merubokkusu/discord-spam-bots#4]
![error](https://user-images.githubusercontent.com/20999549/29918989-29a475c2-8e50-11e7-95ee-2b64e020bb25.png)
![error](https://user-images.githubusercontent.com/20999549/29935588-f03225b8-8e87-11e7-9633-fec7e925d148.png)
And that second error

**Comment by Merubokkusu** [comment]
Can I have the full log?

**Comment by Jeremy2131** [comment]
@Merubokkusu where i can take log?

**Comment by Merubokkusu** [comment]
I just meant to copy paste the entire thing.

But it almost seems that an anti-virus is blocking python from accessing the internet
```
There was not a gateway available to process your request. Wait a bit and retry
``` 
From the discord API.

**Comment by Jeremy2131** [comment]
@Merubokkusu i have only windows defender

**Comment by Merubokkusu** [comment]
🤔
I guess do it again and copy paste the entire thing (even when you started the script)

**Comment by Jeremy2131** [comment]
@Merubokkusu I now added the Python folder to the antivirus exceptions, it can help mb

**Comment by Jeremy2131** [comment]
@Merubokkusu Traceback (most recent call last):
  File "discord_text_spam.py", line 18, in <module>
    client.run(token, bot=False)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 491, in start
    yield from self.connect()
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 444, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 207, in from_client
    timeout=60, loop=client.loop)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 400, in wait_for
    return fut.result()
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 65, in _ensure_coroutine_connect
    ws = yield from websockets.connect(gateway, loop=loop, klass=klass)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\client.py", line 215, in connect
    extra_headers=extra_headers)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\client.py", line 125, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 525
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F213ABACC0>

**Comment by Merubokkusu** [comment]
Are you running the script from "Start.py" or just the text spammer?

**Comment by Jeremy2131** [comment]
Start py

**Comment by Jeremy2131** [comment]
Need only text spammer?

**Comment by Merubokkusu** [comment]
No you are doing it right, config.py is edited with your token right?

**Comment by Jeremy2131** [comment]
@Merubokkusu config edited with my tokens and channel ID are right

**Comment by Jeremy2131** [comment]
@Merubokkusu i just have 7accs in 1 config,can that trigger that error?

**Comment by Merubokkusu** [comment]
It's possible it could break it lol, I'll try and edit the code when I get back to my house.

**Comment by Jeremy2131** [comment]
okay,i'll w8 u,btw now bots works fine...

**Comment by Merubokkusu** [comment]
Just to make sure the way you have the tokens is like this ['token','token'] right?

**Comment by Jeremy2131** [comment]
@Merubokkusu 
![1](https://user-images.githubusercontent.com/20999549/29936548-516c9ad6-8e8b-11e7-8c8c-e670b31d9f52.png)

**Comment by Merubokkusu** [comment]
Yep you did it right, I would delete that image now otherwise people can login to your accounts. 
I'll try and see why it isn't allowing multi when I get back 👍

**Comment by Jeremy2131** [comment]
Thats not my tokens,that my alts,i dont care :D

**Comment by Jeremy2131** [comment]
@Merubokkusu btw i donwload last 'start.py' and i see this.. i think thats not cool 
![1](https://user-images.githubusercontent.com/20999549/29941920-c89d38d4-8e9c-11e7-94a0-1798badd9d25.png)

**Comment by Jeremy2131** [comment]
hey when u come to home :c

**Comment by Merubokkusu** [comment]
My mouse broke so I had to get a new one ¯\_(ツ)_/¯

**Comment by Jeremy2131** [comment]
sadlife,but i still w8 u

**Comment by Merubokkusu** [comment]
![1](https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/40/thinking-face_1f914.png)
Here get all of your accounts to join this server https://discord.gg/t68yeFE
...Yeah I know that's going to take awhile but in the end it will be worth it....maybe

**Comment by Jeremy2131** [comment]
@Merubokkusu so,i do it
