### ISSUE TITLE
is this still even working? - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Merubokkusu/discord-spam-bots#47]
**Describe the bug**
this is the error I get when I try to use DM Spam or any option for that matter...

```
Select a bot: 4
Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 12, in <module>
    import discord
  File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/local/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/local/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 12, in <module>
    import discord
  File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/local/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/local/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Screenshots**
![Screen Shot 2020-04-17 at 11 08 47 am](https://user-images.githubusercontent.com/2242880/79521185-dcbecf00-809b-11ea-9f43-7aafd738d510.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Python Version 3.7.7

**Comment by Merubokkusu** [comment]
Use 3.6
