### ISSUE TITLE
Hi..

### ISSUE THREAD

**Issue by Jeremy2131** [Merubokkusu/discord-spam-bots#5]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "discord_text_spam.py", line 15, in on_ready
    await client.send_message(discord.Object(id=DiscordChannel), spam_text)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "C:\Users\DanoN\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: Gateway Time-out (status code: 504): <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
Again..,idk why

**Comment by Jeremy2131** [comment]
idk why

**Comment by Jeremy2131** [comment]
yesterday works fine,but today after 3 hours i got it

**Comment by Jeremy2131** [comment]
I take that error again,bots worked 5-6 hours and then i take that erorr

**Comment by Merubokkusu** [comment]
Could just be because of using the bots for awhile, Discord probably knows its bots and stops them from working for a bit.

**Comment by Merubokkusu** [comment]
Overall its really something I cant fix. Just wait a bit after you get this message and use it again,

**Comment by Jeremy2131** [comment]
Ye i do it,when take that error i just restart bots,fcking Discord :c
