### ISSUE TITLE
Account Creator Bug

### ISSUE THREAD

**Issue by StudNastty** [Merubokkusu/discord-spam-bots#63]
File "bots/misc/account-creator/account_creator.py", line 66, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 64, in create
    file.writelines(r.json()['token'] + '\n')
KeyError: 'token'
solving captcha...
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 66, in <module>
    create()
  File "bots/misc/account-creator/account_creator.py", line 64, in create
    file.writelines(r.json()['token'] + '\n')
KeyError: 'token'

**Screenshots**

https://i.imgur.com/3cSIG4T.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version Newest version

**Additional context**
Happens if i use more than one email:pass to make accounts

**Comment by dsbilling** [comment]
This should be closed :)
