### ISSUE TITLE
module 'aiohhttp' has no attribute ProxyConnector

### ISSUE THREAD

**Issue by eldrago4** [Merubokkusu/discord-spam-bots#64]
**Describe the bug**
Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 24, in <module>
    conn = aiohttp.ProxyConnector(proxy="http://"+sys.argv[3])
AttributeError: module 'aiohttp' has no attribute 'ProxyConnector'

**To Reproduce**
1. Go to 'start.py'
2. After your tokens are loaded select 4.dm spammer
After this the following error shows up 
Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 24, in <module>
    conn = aiohttp.ProxyConnector(proxy="http://"+sys.argv[3])
AttributeError: module 'aiohttp' has no attribute 'ProxyConnector'

**Expected behavior**
it should spam the dm of server members

**Screenshots**
https://ibb.co/gzVpKmB

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version3.6.4 & 3.8

**Comment by Merubokkusu** [comment]
Discord has blocked self bots, this bot used Discord.py which has also blocked selfbots.
This has been ported to a new API made by arandomnewaccount and I.
Please update the script.
