### ISSUE TITLE
problem with text spam

### ISSUE THREAD

**Issue by ilyanalpha** [Merubokkusu/discord-spam-bots#94]
when i try to use the text spam bot it shows me what's on the screen then the window closes.
can you help me please.
![image](https://user-images.githubusercontent.com/76225934/111292561-975aa700-8648-11eb-875e-45809aa408e8.png)

**Comment by Merubokkusu** [comment]
Update discum

**Comment by crckd-justin** [comment]
How to update it?

**Comment by oztomato** [comment]
im having the same issue it says:

`Traceback (most recent call last):
  File "bots/server/discord_text_spam.py", line 8, in <module>
    import discum
ModuleNotFoundError: No module named 'discum'`

how do i update if thats the problem

**Comment by GGAYUSH123** [comment]
> im having the same issue it says:
> 
> `Traceback (most recent call last): File "bots/server/discord_text_spam.py", line 8, in <module> import discum ModuleNotFoundError: No module named 'discum'`
> 
> how do i update if thats the problem

Type 
pip install discum

**Comment by jufyjug** [comment]
> > im having the same issue it says:
> > `Traceback (most recent call last): File "bots/server/discord_text_spam.py", line 8, in <module> import discum ModuleNotFoundError: No module named 'discum'`
> > how do i update if thats the problem
> 
> Type pip install discum

i tried this and it didnt crash but it showed me this and didnt do anything
![Untitled design](https://github.com/user-attachments/assets/606bb700-60c5-408b-91d3-b25838fc03c0)
